---
namespace: tekne
name: devops
version: 1.3.0
readme: README.md
authors:
  - dvaliente
license:
  - MIT
description: Tekne Arch Linux workstation and server roles
repository: https://github.com/tekne-ops/ansible-collections
issues: https://github.com/tekne-ops/ansible-collections/issues
homepage: https://github.com/tekne-ops/ansible-collections
documentation: https://github.com/tekne-ops/ansible-collections/tree/main/tekne/devops
tags:
  - archlinux
  - desktop
  - docker
  - kubernetes
  - laptop
  - networking
  - server
  - workstation
dependencies:
  amazon.aws: '>=7.0.0'
  ansible.posix: '>=1.5.0'
  community.docker: '>=4.0.0'
  community.general: '>=10.0.0'
