# SPDX-License-Identifier: MIT-0
---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  listen: reload systemd

- name: Reload nftables
  ansible.builtin.systemd:
    name: nftables
    state: reloaded
    daemon_reload: true
  listen: reload nftables
  when: not nftables_install_chroot_phase | bool
