# SPDX-License-Identifier: MIT-0
---
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: reload nftables
  ansible.builtin.systemd:
    name: nftables
    state: reloaded
    daemon_reload: true
  when: not install_chroot_phase | bool
