[Service]
ExecStart=
ExecStart=/bin/sh -c 'nft delete table inet filter 2>/dev/null; exec /usr/sbin/nft -f /etc/nftables.conf'
ExecReload=
ExecReload=/bin/sh -c 'nft delete table inet filter 2>/dev/null; exec /usr/sbin/nft -f /etc/nftables.conf'
ExecStop=
ExecStop=/bin/sh -c 'nft delete table inet filter 2>/dev/null'
