#!/usr/sbin/nft -f

flush ruleset

table inet filter {
    chain input {
        type filter hook input priority filter; policy drop;
        ct state invalid drop
        iif "lo" accept
        udp sport 67 udp dport 68 accept comment "DHCPv4 replies"
        ip protocol icmp icmp type { destination-unreachable, time-exceeded, parameter-problem } accept
        tcp dport 22 accept comment "SSH"
        ct state established,related accept
    }

    chain output {
        type filter hook output priority filter; policy accept;
    }

    chain forward {
        type filter hook forward priority filter; policy drop;
    }
}
