wireplumber.settings = {
    bluetooth.autoswitch-to-headset-profile = false
}

monitor.bluez.properties = {
    bluez5.enable-sbc-xq = true
    bluez5.enable-hw-volume = true
    bluez5.ldac.quality = "hq"
    bluez5.roles = [ a2dp_sink a2dp_source ]

    bluez5.codecs = [
        ldac
        aptx_hd
        aptx_adaptive
        aptx
        aac
        sbc
    ]
}
