[general]
; Soft realtime for games (requires CAP_SYS_NICE / gamemode group)
renice=10
desiredgov=performance
igpu_desiredgov=performance
softrealtime=auto
inhibit_screensaver=1

[gpu]
apply_gpu_optimisations=accept-responsibility
gpu_device=0
nv_powermode=1
nv_core_clock_mhz_offset=0
nv_mem_clock_mhz_offset=0

[cpu]
park_cores=no
pin_cores=yes

[custom]
start=
end=
script_timeout=10
