---
galaxy_info:
  author: dvaliente
  description: QEMU and KVM libvirt packages, groups, and services
  namespace: tekne
  role_name: libvirt
  license: MIT
  min_ansible_version: 2.19.0
  standalone: false
  platforms:
    - name: ArchLinux
      versions:
        - all
  galaxy_tags:
    - archlinux
    - kvm
    - libvirt
collections:
  - community.general
dependencies: []
