# SPDX-License-Identifier: MIT-0
---
# defaults file for n8n
n8n_container_name: n8n
n8n_docker_image: docker.n8n.io/n8nio/n8n
n8n_docker_network: dockers
n8n_docker_ip: 192.168.75.14
n8n_volume_name: n8n_data
n8n_timezone: America/El_Salvador
