# SPDX-License-Identifier: MIT-0
---
# tasks file for jenkins

- name: Create and start Jenkins container
  community.docker.docker_container:
    name: "{{ jenkins_container_name }}"
    image: "{{ jenkins_docker_image }}"
    state: started
    restart_policy: unless-stopped
    networks:
      - name: "{{ jenkins_docker_network }}"
        ipv4_address: "{{ jenkins_docker_ip }}"
    comparisons:
      image: strict
      networks: strict
  tags:
    - jenkins
    - docker
