# SPDX-License-Identifier: MIT-0
---
# Fallback when pipewire runs without the user role in the same play
pipewire_default_group: users

pipewire_users:
  - name: dvaliente
    group: users
  - name: devops
    group: users
