---
argument_specs:
  main:
    short_description: n8n workflow automation container on the dockers network
    description:
      - Runs the n8n workflow automation container on the dockers network.
    options:
      n8n_container_name:
        description: The container name value for the n8n role.
        required: false
        type: str
        default: n8n
      n8n_docker_image:
        description: The docker image value for the n8n role.
        required: false
        type: str
        default: docker.n8n.io/n8nio/n8n:1.113.3
      n8n_docker_network:
        description: The docker network value for the n8n role.
        required: false
        type: str
        default: dockers
      n8n_docker_ip:
        description: The docker ip value for the n8n role.
        required: false
        type: str
        default: 192.168.75.14
      n8n_volume_name:
        description: The volume name value for the n8n role.
        required: false
        type: str
        default: n8n_data
      n8n_timezone:
        description: The timezone value for the n8n role.
        required: false
        type: str
        default: America/El_Salvador
