---
- name: Generate locales
  ansible.builtin.command:
    cmd: /usr/bin/locale-gen
  changed_when: true
  listen: Generate locales

- name: Restart bluetooth
  ansible.builtin.systemd:
    name: bluetooth.service
    state: restarted
  listen: restart bluetooth
  when: ansible_facts['service_mgr'] == 'systemd'
