---
- name: Restart systemd-networkd
  ansible.builtin.systemd:
    name: systemd-networkd.service
    state: restarted
  when: not network_install_chroot_phase | bool
  listen: Restart systemd-networkd

- name: Restart systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved.service
    state: restarted
  when: not network_install_chroot_phase | bool
  listen: Restart systemd-resolved

- name: Restart TLP
  ansible.builtin.systemd:
    name: tlp.service
    state: restarted
  when: not network_install_chroot_phase | bool
