# SPDX-License-Identifier: MIT-0
---
nftables_hostname: "{{ hostname | default(ansible_hostname) | upper }}"

nftables_server_hosts:
  - THEMIS

nftables_docker_hosts:
  - THEMIS
  - YUGEN

install_chroot_phase: false
